<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>OpenKey.Providers.OpenRouter</RootNamespace>
    <AssemblyName>OpenKey.Providers.OpenRouter</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenKey.Core\OpenKey.Core.csproj" />
  </ItemGroup>
</Project>
