using OpenKey.Core.Providers;

namespace OpenKey.Core.Storage;

/// <summary>One conversation, as stored. Shape is normative — see docs/05-persistence-and-reset.md.</summary>
public sealed record Chat(
    string Id,
    string Title,
    string ModelId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    IReadOnlyList<ChatMessage> Turns)
{
    /// <summary>Longest title kept. Long enough to recognise a chat, short enough for a sidebar.</summary>
    public const int MaxTitleLength = 48;

    public const string Untitled = "New chat";

    /// <summary>
    /// A title taken from the opening message rather than generated by a model: a title is
    /// cosmetic and renameable, and paying tokens and latency for one on every new chat is a bad
    /// trade.
    /// </summary>
    public static string TitleFrom(IEnumerable<ChatMessage> turns)
    {
        var first = turns.FirstOrDefault(t => t.Role == ChatMessage.UserRole)?.Content;
        if (string.IsNullOrWhiteSpace(first)) return Untitled;

        var flat = first.ReplaceLineEndings(" ").Trim();
        while (flat.Contains("  ", StringComparison.Ordinal))
            flat = flat.Replace("  ", " ", StringComparison.Ordinal);

        return flat.Length <= MaxTitleLength ? flat : flat[..(MaxTitleLength - 1)].TrimEnd() + "…";
    }
}

/// <summary>
/// A chat as it appears in a list. Kept separate from <see cref="Chat"/> so drawing a sidebar does
/// not mean reading and parsing every conversation on disk.
/// </summary>
public sealed record ChatSummary(string Id, string Title, DateTimeOffset UpdatedAt, int MessageCount);

/// <summary>
/// Conversations on disk. Replaces the single-session store: OpenKey used to keep exactly one
/// conversation, so starting another meant destroying the previous one.
/// </summary>
public interface IChatStore
{
    /// <summary>Newest first. Never throws — an unreadable store lists nothing rather than failing a launch.</summary>
    Task<IReadOnlyList<ChatSummary>> ListAsync(CancellationToken ct);

    Task<Chat?> LoadAsync(string id, CancellationToken ct);

    Task SaveAsync(Chat chat, CancellationToken ct);

    Task DeleteAsync(string id, CancellationToken ct);

    /// <summary>The chat to open on launch, or null when there are none.</summary>
    Task<string?> MostRecentIdAsync(CancellationToken ct);

    /// <summary>Removes every conversation. Used by the reset path.</summary>
    void Clear();

    /// <summary>A new, unused identifier. Sortable by time, and safe as a filename.</summary>
    static string NewId() =>
        $"{DateTimeOffset.UtcNow:yyyyMMdd-HHmmss}-{Guid.NewGuid().ToString("N")[..6]}";
}
